"""Tool implementations for blue_pill.

Every tool returns a string (results or an error message). Tools never raise:
errors go back to the model as text so a wake can't crash on a bad tool call.
"""

import json
import os
import re
import subprocess
import time
from pathlib import Path

import requests

REPO_ROOT = Path(__file__).resolve().parent.parent

# Paths the agent cannot write to via file tools. Shell writes to these are
# reverted by the workflow before commit; the ledger is regenerated by agent.py.
PROTECTED_WRITE = (".github", "scripts", "memory/ledger.md", "memory/ledger.json", ".env")

SHELL_TIMEOUT = 60
MAX_TOOL_OUTPUT = 10_000   # chars returned to the model per tool call
MAX_FETCH_OUTPUT = 20_000

AGENTMAIL_BASE = "https://api.agentmail.to/v0"
USER_AGENT = "blue_pill-agent/1.0"


# ---------------------------------------------------------------- files

def _safe_path(rel_path: str, write: bool = False) -> Path:
    p = (REPO_ROOT / rel_path).resolve()
    if not p.is_relative_to(REPO_ROOT):
        raise ValueError(f"path escapes repository: {rel_path}")
    if write:
        rel = p.relative_to(REPO_ROOT).as_posix()
        for prot in PROTECTED_WRITE:
            if rel == prot or rel.startswith(prot + "/"):
                raise ValueError(f"'{rel}' is read-only")
    return p


def read_file(path: str) -> str:
    p = _safe_path(path)
    if not p.is_file():
        return f"error: no such file: {path}"
    text = p.read_text(errors="replace")
    if len(text) > MAX_TOOL_OUTPUT:
        return text[:MAX_TOOL_OUTPUT] + f"\n...[truncated, file is {len(text)} chars]"
    return text


def write_file(path: str, content: str) -> str:
    try:
        p = _safe_path(path, write=True)
    except ValueError as e:
        return f"error: {e}"
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content)
    return f"wrote {len(content)} chars to {path}"


def edit_file(path: str, old: str, new: str) -> str:
    try:
        p = _safe_path(path, write=True)
    except ValueError as e:
        return f"error: {e}"
    if not p.is_file():
        return f"error: no such file: {path}"
    text = p.read_text(errors="replace")
    n = text.count(old)
    if n == 0:
        return "error: old string not found in file"
    if n > 1:
        return f"error: old string appears {n} times; provide a unique string"
    p.write_text(text.replace(old, new, 1))
    return f"edited {path}"


# ---------------------------------------------------------------- shell

def shell(command: str) -> str:
    try:
        r = subprocess.run(
            command, shell=True, cwd=REPO_ROOT, timeout=SHELL_TIMEOUT,
            capture_output=True, text=True,
        )
    except subprocess.TimeoutExpired:
        return f"error: command timed out after {SHELL_TIMEOUT}s"
    out = (r.stdout or "") + (("\n[stderr]\n" + r.stderr) if r.stderr else "")
    out = out.strip() or "(no output)"
    if r.returncode != 0:
        out = f"[exit code {r.returncode}]\n{out}"
    return out[:MAX_TOOL_OUTPUT]


# ---------------------------------------------------------------- web

def web_fetch(url: str) -> str:
    try:
        r = requests.get(url, headers={"User-Agent": USER_AGENT}, timeout=25)
    except requests.RequestException as e:
        return f"error: fetch failed: {e}"
    ctype = r.headers.get("content-type", "")
    text = r.text
    if "html" in ctype or text.lstrip()[:1] == "<":
        text = re.sub(r"(?is)<(script|style|noscript)[^>]*>.*?</\1>", " ", text)
        text = re.sub(r"(?s)<[^>]+>", " ", text)
        text = re.sub(r"[ \t]+", " ", text)
        text = re.sub(r"\n\s*\n+", "\n", text)
    out = f"[HTTP {r.status_code}] {url}\n{text.strip()}"
    return out[:MAX_FETCH_OUTPUT]


# ---------------------------------------------------------------- email

def _am_headers():
    key = os.environ.get("AGENTMAIL_API_KEY")
    if not key:
        raise RuntimeError("AGENTMAIL_API_KEY not configured")
    return {"Authorization": f"Bearer {key}"}


def _inbox_id():
    inbox = os.environ.get("AGENTMAIL_INBOX")
    if not inbox:
        raise RuntimeError("AGENTMAIL_INBOX not configured")
    return inbox


def email_check() -> str:
    try:
        inbox = _inbox_id()
        r = requests.get(
            f"{AGENTMAIL_BASE}/inboxes/{inbox}/messages",
            headers=_am_headers(), params={"labels": "unread", "limit": 10}, timeout=25,
        )
        r.raise_for_status()
        msgs = r.json().get("messages", [])
        if not msgs:
            return "no unread messages"
        out = []
        for m in msgs:
            mid = m["message_id"]
            body = m.get("preview", "")
            try:
                d = requests.get(
                    f"{AGENTMAIL_BASE}/inboxes/{inbox}/messages/{mid}",
                    headers=_am_headers(), timeout=25,
                )
                d.raise_for_status()
                body = d.json().get("text") or body
            except requests.RequestException:
                pass
            out.append({
                "from": m.get("from"),
                "subject": m.get("subject"),
                "timestamp": m.get("timestamp"),
                "body": (body or "")[:4000],
            })
            # mark as read (best effort)
            try:
                requests.patch(
                    f"{AGENTMAIL_BASE}/inboxes/{inbox}/messages/{mid}",
                    headers=_am_headers(), json={"remove_labels": ["unread"]}, timeout=25,
                )
            except requests.RequestException:
                pass
        return json.dumps(out, indent=2)[:MAX_TOOL_OUTPUT]
    except (RuntimeError, requests.RequestException) as e:
        return f"error: {e}"


def email_send(to: str, subject: str, body: str) -> str:
    try:
        inbox = _inbox_id()
        r = requests.post(
            f"{AGENTMAIL_BASE}/inboxes/{inbox}/messages/send",
            headers=_am_headers(),
            json={"to": to, "subject": subject, "text": body},
            timeout=25,
        )
        r.raise_for_status()
        return f"sent to {to} (message_id: {r.json().get('message_id')})"
    except (RuntimeError, requests.RequestException) as e:
        return f"error: {e}"


# ---------------------------------------------------------------- stripe

def _stripe():
    import stripe
    key = os.environ.get("STRIPE_API_KEY")
    if not key:
        raise RuntimeError("STRIPE_API_KEY not configured")
    stripe.api_key = key
    return stripe


def stripe_create_payment_link(amount_usd: float, description: str) -> str:
    try:
        stripe = _stripe()
        cents = int(round(float(amount_usd) * 100))
        if cents < 50:
            return "error: minimum amount is $0.50"
        price = stripe.Price.create(
            unit_amount=cents, currency="usd",
            product_data={"name": description[:250]},
        )
        link = stripe.PaymentLink.create(line_items=[{"price": price.id, "quantity": 1}])
        return f"payment link for ${cents / 100:.2f} ({description}): {link.url}"
    except Exception as e:
        return f"error: {e}"


def stripe_balance() -> str:
    try:
        stripe = _stripe()
        b = stripe.Balance.retrieve()
        fmt = lambda items: ", ".join(f"${i['amount'] / 100:.2f} {i['currency']}" for i in items) or "$0.00"
        return f"available: {fmt(b['available'])} | pending: {fmt(b['pending'])}"
    except Exception as e:
        return f"error: {e}"


def stripe_list_payments() -> str:
    try:
        payments = list_succeeded_payments()
        if not payments:
            return "no payments received"
        lines = [
            f"{p['created']}  ${p['amount_usd']:.2f}  {p['description'] or '(no description)'}"
            for p in payments
        ]
        return "\n".join(lines)[:MAX_TOOL_OUTPUT]
    except Exception as e:
        return f"error: {e}"


def list_succeeded_payments():
    """Used by both the tool and the ledger sync in agent.py."""
    from datetime import datetime, timezone
    stripe = _stripe()
    out = []
    for pi in stripe.PaymentIntent.list(limit=100).auto_paging_iter():
        if pi.status == "succeeded":
            out.append({
                "id": pi.id,
                "amount_usd": pi.amount_received / 100,
                "description": pi.description,
                "created": datetime.fromtimestamp(pi.created, tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            })
    return out


# ---------------------------------------------------------------- wallet (USDC on Base)

BASE_RPC_DEFAULT = "https://mainnet.base.org"
BASE_CHAIN_ID = 8453
USDC_CONTRACT = "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"  # native USDC on Base
USDC_DECIMALS = 6

ERC20_ABI = [
    {"name": "balanceOf", "type": "function", "stateMutability": "view",
     "inputs": [{"name": "account", "type": "address"}],
     "outputs": [{"name": "", "type": "uint256"}]},
    {"name": "transfer", "type": "function", "stateMutability": "nonpayable",
     "inputs": [{"name": "to", "type": "address"}, {"name": "amount", "type": "uint256"}],
     "outputs": [{"name": "", "type": "bool"}]},
]


def _wallet_account():
    from eth_account import Account
    key = os.environ.get("WALLET_PRIVATE_KEY")
    if not key:
        raise RuntimeError("WALLET_PRIVATE_KEY not configured")
    return Account.from_key(key)


def _w3():
    from web3 import Web3
    # `or` (not .get's default arg) because CI sets this var to "" when the
    # optional BASE_RPC_URL secret isn't configured, rather than omitting it.
    rpc = os.environ.get("BASE_RPC_URL") or BASE_RPC_DEFAULT
    last_err = None
    for attempt in range(3):
        if attempt:
            time.sleep(2 * attempt)  # 2s, then 4s
        try:
            w3 = Web3(Web3.HTTPProvider(rpc, request_kwargs={"timeout": 25}))
            if w3.is_connected():
                return w3
        except Exception as e:
            last_err = e
    detail = f" ({last_err})" if last_err else ""
    raise RuntimeError(f"cannot reach Base RPC at {rpc} after 3 attempts{detail}")


def wallet_address() -> str:
    """Address string, or None if no wallet configured. Used by agent.py."""
    try:
        return _wallet_account().address
    except RuntimeError:
        return None


def usdc_balance() -> float:
    """USDC balance in dollars. Used by the ledger sync in agent.py."""
    w3 = _w3()
    acct = _wallet_account()
    usdc = w3.eth.contract(address=USDC_CONTRACT, abi=ERC20_ABI)
    return usdc.functions.balanceOf(acct.address).call() / 10**USDC_DECIMALS


def wallet_balance() -> str:
    try:
        w3 = _w3()
        acct = _wallet_account()
        usdc = usdc_balance()
        eth = w3.eth.get_balance(acct.address) / 1e18
        return (f"address: {acct.address}\n"
                f"USDC: ${usdc:.4f}\n"
                f"ETH (for transaction fees): {eth:.6f}")
    except Exception as e:
        return f"error: {e}"


def wallet_send_usdc(to_address: str, amount_usd: float) -> str:
    try:
        from web3 import Web3
        w3 = _w3()
        acct = _wallet_account()
        if not Web3.is_address(to_address):
            return f"error: invalid address: {to_address}"
        to = Web3.to_checksum_address(to_address)
        atomic = int(round(float(amount_usd) * 10**USDC_DECIMALS))
        if atomic <= 0:
            return "error: amount must be positive"
        have = int(usdc_balance() * 10**USDC_DECIMALS)
        if atomic > have:
            return f"error: insufficient USDC (have ${have / 10**USDC_DECIMALS:.4f})"
        usdc = w3.eth.contract(address=USDC_CONTRACT, abi=ERC20_ABI)
        tx = usdc.functions.transfer(to, atomic).build_transaction({
            "from": acct.address,
            "nonce": w3.eth.get_transaction_count(acct.address),
            "chainId": BASE_CHAIN_ID,
        })
        tx["gas"] = w3.eth.estimate_gas(tx)
        signed = acct.sign_transaction(tx)
        tx_hash = w3.eth.send_raw_transaction(signed.raw_transaction)
        receipt = w3.eth.wait_for_transaction_receipt(tx_hash, timeout=120)
        status = "confirmed" if receipt.status == 1 else "FAILED"
        return f"sent ${atomic / 10**USDC_DECIMALS:.4f} USDC to {to}: {status} (tx {tx_hash.hex()})"
    except Exception as e:
        return f"error: {e}"


def x402_fetch(url: str, max_usd: float = 0.10, method: str = "GET") -> str:
    """Fetch an x402-priced (HTTP 402) resource, paying automatically with USDC
    if the price is within max_usd."""
    try:
        acct = _wallet_account()
        from x402 import x402ClientSync
        from x402.client import max_amount
        from x402.http.clients import x402_requests
        from x402.mechanisms.evm import EthAccountSigner
        from x402.mechanisms.evm.exact.register import register_exact_evm_client

        cap_atomic = int(round(float(max_usd) * 10**USDC_DECIMALS))
        price_filter = max_amount(cap_atomic)

        def capped_selector(version, reqs):
            ok = price_filter(version, reqs)
            if not ok:
                cheapest = min(int(r.get_amount()) for r in reqs) / 10**USDC_DECIMALS
                raise ValueError(
                    f"price exceeds cap: cheapest option is ${cheapest:.4f}, cap is ${max_usd:.4f}")
            return ok[0]

        client = x402ClientSync(payment_requirements_selector=capped_selector)
        register_exact_evm_client(client, EthAccountSigner(acct))

        with x402_requests(client) as session:
            r = session.request(method.upper(), url, timeout=30,
                                headers={"User-Agent": USER_AGENT})
        text = r.text
        if "html" in r.headers.get("content-type", ""):
            text = re.sub(r"(?is)<(script|style|noscript)[^>]*>.*?</\1>", " ", text)
            text = re.sub(r"(?s)<[^>]+>", " ", text)
            text = re.sub(r"\s+", " ", text)
        return f"[HTTP {r.status_code}] {url}\n{text.strip()}"[:MAX_FETCH_OUTPUT]
    except Exception as e:
        return f"error: {e}"


# ---------------------------------------------------------------- publish

SITE_PATH = "docs/index.md"
SITE_URL = "https://andrew-somerset.github.io/blue_pill/"


def publish_note(markdown: str) -> str:
    p = REPO_ROOT / SITE_PATH
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(markdown)
    return f"published {len(markdown)} chars to {SITE_URL} (live after this wake's commit)"


# ---------------------------------------------------------------- registry

TOOL_SPECS = [
    {
        "name": "read_file",
        "description": "Read a file in the repository. Path is relative to the repo root.",
        "input_schema": {
            "type": "object",
            "properties": {"path": {"type": "string"}},
            "required": ["path"],
        },
    },
    {
        "name": "write_file",
        "description": "Create or overwrite a file in the repository. Some paths are read-only (see TOOLS.md).",
        "input_schema": {
            "type": "object",
            "properties": {"path": {"type": "string"}, "content": {"type": "string"}},
            "required": ["path", "content"],
        },
    },
    {
        "name": "edit_file",
        "description": "Replace one exact, unique occurrence of a string in a file.",
        "input_schema": {
            "type": "object",
            "properties": {
                "path": {"type": "string"},
                "old": {"type": "string"},
                "new": {"type": "string"},
            },
            "required": ["path", "old", "new"],
        },
    },
    {
        "name": "shell",
        "description": "Run a shell command in the repository directory. 60-second timeout.",
        "input_schema": {
            "type": "object",
            "properties": {"command": {"type": "string"}},
            "required": ["command"],
        },
    },
    {
        "name": "web_fetch",
        "description": "Fetch a URL and return its text content (HTML is stripped to text).",
        "input_schema": {
            "type": "object",
            "properties": {"url": {"type": "string"}},
            "required": ["url"],
        },
    },
    {
        "name": "email_check",
        "description": "List unread messages in your email inbox, with bodies. Marks them as read.",
        "input_schema": {"type": "object", "properties": {}},
    },
    {
        "name": "email_send",
        "description": "Send an email from your inbox.",
        "input_schema": {
            "type": "object",
            "properties": {
                "to": {"type": "string"},
                "subject": {"type": "string"},
                "body": {"type": "string"},
            },
            "required": ["to", "subject", "body"],
        },
    },
    {
        "name": "stripe_create_payment_link",
        "description": "Create a Stripe payment link anyone can pay at. Amount in USD, minimum $0.50.",
        "input_schema": {
            "type": "object",
            "properties": {
                "amount_usd": {"type": "number"},
                "description": {"type": "string"},
            },
            "required": ["amount_usd", "description"],
        },
    },
    {
        "name": "stripe_balance",
        "description": "Check the Stripe account balance.",
        "input_schema": {"type": "object", "properties": {}},
    },
    {
        "name": "stripe_list_payments",
        "description": "List payments received in the Stripe account.",
        "input_schema": {"type": "object", "properties": {}},
    },
    {
        "name": "wallet_balance",
        "description": "Check your crypto wallet on the Base network: USDC balance and ETH (used for transaction fees).",
        "input_schema": {"type": "object", "properties": {}},
    },
    {
        "name": "wallet_send_usdc",
        "description": "Send USDC from your wallet to any Base address. Requires a small amount of ETH for the network fee.",
        "input_schema": {
            "type": "object",
            "properties": {
                "to_address": {"type": "string"},
                "amount_usd": {"type": "number"},
            },
            "required": ["to_address", "amount_usd"],
        },
    },
    {
        "name": "x402_fetch",
        "description": (
            "Fetch a URL that charges per request via the x402 protocol (HTTP 402). "
            "Pays automatically from your USDC if the price is at or below max_usd "
            "(default $0.10); otherwise returns the price without paying. "
            "Machine-priced APIs and services run by other agents commonly use x402."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "url": {"type": "string"},
                "max_usd": {"type": "number", "description": "Highest price you are willing to pay. Default 0.10."},
                "method": {"type": "string", "enum": ["GET", "POST"], "description": "Default GET."},
            },
            "required": ["url"],
        },
    },
    {
        "name": "publish_note",
        "description": f"Replace the contents of your public web page ({SITE_URL}) with the given markdown.",
        "input_schema": {
            "type": "object",
            "properties": {"markdown": {"type": "string"}},
            "required": ["markdown"],
        },
    },
]

_HANDLERS = {
    "read_file": lambda i: read_file(i["path"]),
    "write_file": lambda i: write_file(i["path"], i["content"]),
    "edit_file": lambda i: edit_file(i["path"], i["old"], i["new"]),
    "shell": lambda i: shell(i["command"]),
    "web_fetch": lambda i: web_fetch(i["url"]),
    "email_check": lambda i: email_check(),
    "email_send": lambda i: email_send(i["to"], i["subject"], i["body"]),
    "stripe_create_payment_link": lambda i: stripe_create_payment_link(i["amount_usd"], i["description"]),
    "stripe_balance": lambda i: stripe_balance(),
    "stripe_list_payments": lambda i: stripe_list_payments(),
    "wallet_balance": lambda i: wallet_balance(),
    "wallet_send_usdc": lambda i: wallet_send_usdc(i["to_address"], i["amount_usd"]),
    "x402_fetch": lambda i: x402_fetch(i["url"], i.get("max_usd", 0.10), i.get("method", "GET")),
    "publish_note": lambda i: publish_note(i["markdown"]),
}


def run_tool(name: str, tool_input: dict) -> str:
    handler = _HANDLERS.get(name)
    if handler is None:
        return f"error: unknown tool: {name}"
    try:
        return handler(tool_input or {})
    except KeyError as e:
        return f"error: missing required parameter: {e}"
    except Exception as e:  # last-resort guard; tools shouldn't raise
        return f"error: {type(e).__name__}: {e}"
